sudo: false
language: c++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - scons
    - gcc-4.8
    - g++-4.8
    - libeigen3-dev
    - libprotobuf-dev
    - protobuf-compiler
install:
  - uname -a
  - g++ --version
  - ls /usr/bin/g++*
script:
  - scons CXX=g++-4.8
